services:
  python-app:
    build: .
    container_name: python-app
    restart: always
    env_file:
      - .env
    volumes:
      - integrador_data:/var/lib/python-app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - rabbitmq_rabbitmq_network
      - api_erp_mynetwork

volumes:
  integrador_data:

networks:
  rabbitmq_rabbitmq_network:
    external: true
  api_erp_mynetwork:
    external: true
